export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_TODOS = 'FETCH_TODOS'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_TODO = 'FETCH_TODO'
export const FETCH_COMMENT = 'FETCH_COMMENT'


export const FETCH_USERS_LIST = 'FETCH_USER'
export const FETCH_TODOS_LIST = 'FETCH_TODO'
export const FETCH_COMMENTS_LIST = 'FETCH_COMMENT'

export const SELECT_GRID_ITEM = 'SELECT_GRID_ITEM';